# Test suite must pass on both Travis and AppVeyor before merging into `master`.
status = [
    "continuous-integration/travis-ci/push"
]

# Do not allow pull requests with these labels to be merged.
block_labels = [
    "status: postponed",
    "status: stalled",
    "status: wontfix",
    "status: working"
]
